/**
 * Token-based auto-compact for cursor-runner — a Cursor-side analog of the
 * Claude Agent SDK PreCompact hook (see container/agent-runner/src/index.ts).
 *
 * Cursor stream-json does NOT emit a compact event, and cursor-agent has no
 * public hook for "context window approaching". The closest signal we have
 * is `result.usage.{inputTokens,outputTokens}` per turn. cursor-runner
 * accumulates these and, when the running total crosses a threshold, archives
 * the conversation log to `<workspaceGroup>/conversations/` and starts the
 * next turn without `--resume <chatId>` (forcing a fresh Cursor chat).
 *
 * Trade-off vs Claude PreCompact:
 *   - Claude SDK does in-place compaction (summary replaces history). We
 *     can't do that — Cursor manages context server-side and exposes no
 *     "summarize and continue" API.
 *   - We start a fresh chat instead. Continuity is preserved by archiving
 *     all user/assistant turns to a markdown file the user (or future
 *     cursor-runner runs) can re-inject as context if needed.
 *
 * Threshold is configured via `CURSOR_AUTO_COMPACT_TOKENS` env var. `0`
 * disables (default) — turn off auto-compact and rely on cursor-agent
 * surfacing context-window errors directly. Suggested values:
 *   - 200_000 for Sonnet 4.6 1M (compact at ~20% capacity, conservative)
 *   - 800_000 for Sonnet 4.6 1M (compact at ~80% capacity, aggressive)
 */
import fs from 'fs';
import path from 'path';

export interface ArchiveEntry {
  /** ISO 8601 timestamp when the turn finished. */
  timestamp: string;
  /** Combined user prompt text for this turn (may include drained IPC). */
  user: string;
  /** Final assistant text returned by cursor-agent. */
  assistant: string;
  /** Per-turn token counts (sum of input + output across the cursor-agent run). */
  inputTokens: number;
  outputTokens: number;
}

export interface AutoCompactState {
  log: ArchiveEntry[];
  /** Sum of all turns' inputTokens + outputTokens since last reset. */
  cumulativeTokens: number;
}

/** Initial state factory — exported so tests don't depend on the literal {}. */
export function createState(): AutoCompactState {
  return { log: [], cumulativeTokens: 0 };
}

/** Append one turn to the log + bump cumulative tokens. Pure mutation on `state`. */
export function pushTurn(state: AutoCompactState, entry: ArchiveEntry): void {
  state.log.push(entry);
  state.cumulativeTokens += entry.inputTokens + entry.outputTokens;
}

/**
 * Reset state in-place (history archived, fresh start). Returns the previous
 * state so callers can pass it to buildArchiveMarkdown if they want to log
 * what just got archived.
 */
export function resetState(state: AutoCompactState): AutoCompactState {
  const prev: AutoCompactState = {
    log: state.log,
    cumulativeTokens: state.cumulativeTokens,
  };
  state.log = [];
  state.cumulativeTokens = 0;
  return prev;
}

/** Compact decision. Threshold <= 0 disables. */
export function shouldCompact(
  state: AutoCompactState,
  threshold: number,
): boolean {
  return threshold > 0 && state.cumulativeTokens >= threshold;
}

export interface ArchiveMeta {
  groupFolder: string;
  chatId: string | undefined;
  archivedAt: string;
  threshold: number;
}

/** Render a markdown archive of the entries. Pure function — no IO. */
export function buildArchiveMarkdown(
  entries: ArchiveEntry[],
  meta: ArchiveMeta,
): string {
  const totalIn = entries.reduce((s, e) => s + e.inputTokens, 0);
  const totalOut = entries.reduce((s, e) => s + e.outputTokens, 0);

  const header = [
    '# Cursor Auto-Compact Archive',
    '',
    `- Group: ${meta.groupFolder}`,
    `- Cursor chat ID: ${meta.chatId ?? '(none — first turn)'}`,
    `- Archived at: ${meta.archivedAt}`,
    `- Threshold: ${meta.threshold} tokens`,
    `- Turns: ${entries.length}`,
    `- Tokens: input=${totalIn}, output=${totalOut}, total=${totalIn + totalOut}`,
    '',
    '_Auto-generated by cursor-runner because cumulative tokens crossed `CURSOR_AUTO_COMPACT_TOKENS`. The next cursor-agent invocation will start a fresh chat (no `--resume`). To restore context, paste the relevant turns into the next prompt._',
    '',
    '---',
    '',
  ].join('\n');

  const body = entries
    .map((e, i) => {
      const u = e.user.length > 4000 ? e.user.slice(0, 4000) + '\n…(truncated)' : e.user;
      const a = e.assistant.length > 4000 ? e.assistant.slice(0, 4000) + '\n…(truncated)' : e.assistant;
      return [
        `## Turn ${i + 1} — ${e.timestamp}`,
        '',
        `_input=${e.inputTokens}, output=${e.outputTokens}_`,
        '',
        '**User**:',
        '',
        u,
        '',
        '**Assistant**:',
        '',
        a,
        '',
      ].join('\n');
    })
    .join('---\n\n');

  return header + body;
}

/**
 * Atomic-write the archive into `<workspaceGroup>/conversations/<filename>.md`
 * (mirrors agent-runner's PreCompact archive layout). Returns the absolute
 * path written, or empty string when content is empty (no-op).
 */
export function writeArchive(
  workspaceGroup: string,
  filenameBase: string,
  content: string,
): string {
  if (!content) return '';
  const dir = path.join(workspaceGroup, 'conversations');
  fs.mkdirSync(dir, { recursive: true });
  // Sanitize filenameBase: replace path traversal sequences (`..`) and any
  // non-alphanumeric/underscore/dash with a single dash. We deliberately
  // strip dots entirely — caller appends `.md`, so leaving dots in the base
  // would double up extensions and let `..` slip through after collapsing.
  const safe = filenameBase
    .replace(/\.+/g, '-')
    .replace(/[^A-Za-z0-9_-]/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 80);
  const file = path.join(dir, `${safe}.md`);
  const tmp = file + '.tmp';
  fs.writeFileSync(tmp, content);
  fs.renameSync(tmp, file);
  return file;
}

/** Suggest a filename base from chatId + timestamp. */
export function defaultArchiveName(
  chatId: string | undefined,
  timestamp: string,
): string {
  const ts = timestamp.replace(/[:.]/g, '-');
  return `${ts}-cursor-${(chatId || 'first').slice(0, 12)}`;
}
