/**
 * Build the per-turn `<workspaceGroup>/AGENTS.md` for cursor-agent.
 *
 * cursor-agent has no `--system-prompt` flag; the supported way to inject
 * happyclaw's behavior guidelines is via the project-level `AGENTS.md` file
 * cursor-agent auto-loads when invoked with `--workspace=<groupDir>`. We
 * regenerate this file before every cursor-agent invocation so dynamic
 * dimensions (channel format / isHome memory variant / conversation-agent
 * override / disableMemoryLayer) are always fresh for the current turn.
 *
 * Source of truth is `container/agent-runner/prompts/`. cursor-runner does
 * not maintain its own copy — duplicating prompts would mean every prompt
 * tweak needs two PRs. The host (container-runner.ts) sets
 * `HAPPYCLAW_PROMPTS_DIR` at spawn time so cursor-runner reads from the
 * canonical location regardless of host vs container mode.
 *
 * Layout of generated AGENTS.md (sections may be omitted based on context):
 *   # HappyClaw Agent Behavior
 *   ## Interaction
 *   ## Skill routing
 *   ## Security
 *   ## Memory system          (skipped when disableMemoryLayer)
 *   ## Output guidelines
 *   ## Web fetch
 *   ## Background tasks
 *   ## Channel format         (only when chatJid maps to a known channel)
 *   ## Conversation agent override   (only when running inside a sub-agent)
 */
import fs from 'fs';
import path from 'path';

import { getChannelFromJid } from './channel-prefixes.js';

export interface AgentsMdContext {
  /** Group is one of the user's home containers (admin or member). */
  isHome: boolean;
  /** JID identifying the IM channel (or web:* for direct workspace messages). */
  chatJid: string;
  /** True when this turn runs as a conversation-agent sub-agent — adds the
   * agent-override.md guidance section. */
  hasConversationAgentOverride: boolean;
  /** Disable the memory-system section entirely (matches agent-runner's
   * `HAPPYCLAW_DISABLE_MEMORY_LAYER=true` mode). */
  disableMemoryLayer: boolean;
  /** Absolute path to `container/agent-runner/prompts/` on the host, or its
   * symlinked counterpart inside a container. Set by container-runner.ts via
   * the `HAPPYCLAW_PROMPTS_DIR` env var. */
  promptsDir: string;
  /** Cursor model identifier passed to `cursor-agent --model`. Surfaced in the
   * runtime-identity section so the LLM can answer "which model are you?"
   * accurately instead of guessing from training data. */
  cursorModel: string;
}

const FILE_HEADER = [
  '# HappyClaw Agent Behavior',
  '',
  '_This file is auto-generated by cursor-runner before every cursor-agent invocation. Do NOT edit — sources live in `container/agent-runner/prompts/`. Manual changes will be overwritten on the next turn._',
  '',
].join('\n');

/**
 * Identity preamble injected at the top of every cursor-runner AGENTS.md.
 * Counters the LLM's training-time assumption that it is running on the
 * Claude Agent SDK by stating the actual stack explicitly. The model name is
 * interpolated so users can verify the exact build through the UI.
 *
 * Kept as a const string (not a `prompts/` file) because agent-runner shares
 * the same prompts dir but runs on a different stack — we don't want this
 * section bleeding into Claude SDK turns.
 */
function runtimeIdentityBlock(model: string): string {
  return [
    'You are running as the **Cursor backend** of the HappyClaw multi-agent platform.',
    '',
    '- Runtime: `cursor-agent` CLI driven by HappyClaw\'s `cursor-runner`. Not the Claude Agent SDK.',
    `- Model: \`${model}\` (Cursor\'s repackaging — the underlying weights are Anthropic\'s, but the request path is Cursor CLI \u2192 Cursor backend).`,
    '- Tooling: built-in Cursor tools (Read/Edit/Shell/Task/…) plus HappyClaw MCP tools loaded from `<workspace>/.cursor/mcp.json` (prefix `mcp__happyclaw__*`).',
    '',
    'When the user asks "which model" or "which SDK", answer with the facts above. Do not say "Claude Agent SDK" — that is the *other* HappyClaw backend (selectable per user / per group), and this conversation is not on it.',
  ].join('\n');
}

interface Section {
  title: string;
  body: string;
}

function loadOptional(promptsDir: string, file: string): string | null {
  try {
    return fs.readFileSync(path.join(promptsDir, file), 'utf-8').trimEnd();
  } catch {
    return null;
  }
}

function buildSections(ctx: AgentsMdContext): Section[] {
  const sections: Section[] = [];
  const push = (title: string, file: string) => {
    const body = loadOptional(ctx.promptsDir, file);
    if (body) sections.push({ title, body });
  };

  // Runtime identity FIRST — overrides the LLM's training-time guess about
  // its own stack before any other behavior section is read.
  sections.push({
    title: 'Runtime identity',
    body: runtimeIdentityBlock(ctx.cursorModel),
  });

  push('Interaction', 'interaction.md');
  push('Skill routing', 'skill-routing.md');
  push('Security', 'security-rules.md');

  if (!ctx.disableMemoryLayer) {
    push(
      'Memory system',
      ctx.isHome ? 'memory-system.home.md' : 'memory-system.guest.md',
    );
  }

  push('Output guidelines', 'output.md');
  push('Web fetch', 'web-fetch.md');
  push('Background tasks', 'background-tasks.md');

  // Channel-specific format hints (feishu / telegram / qq / dingtalk / …).
  // 'web' or unrecognized prefix → no channel section (web messages have no
  // platform-specific formatting requirements).
  const channel = getChannelFromJid(ctx.chatJid);
  if (channel !== 'web') {
    const channelBody = loadOptional(
      ctx.promptsDir,
      path.join('channels', `${channel}.md`),
    );
    if (channelBody) {
      sections.push({ title: `Channel format (${channel})`, body: channelBody });
    }
  }

  if (ctx.hasConversationAgentOverride) {
    push('Conversation agent override', 'agent-override.md');
  }

  return sections;
}

/**
 * Render the AGENTS.md content. Pure function — caller writes to disk.
 *
 * Always emits at minimum the Runtime-identity block, so cursor-agent never
 * loses sight of the fact that it is the cursor-runner stack. When promptsDir
 * is missing we still emit identity-only — agent-runner's prompts being
 * unavailable is a deployment gap, not a reason to forget what backend we are.
 */
export function buildAgentsMd(ctx: AgentsMdContext): string {
  const sections = buildSections(ctx);
  // The identity block is always pushed first (see buildSections), so
  // sections is guaranteed non-empty regardless of whether promptsDir exists.
  const body = sections
    .map((s) => `## ${s.title}\n\n${s.body}`)
    .join('\n\n');
  return `${FILE_HEADER}\n${body}\n`;
}

/**
 * Atomically write `<workspaceGroup>/AGENTS.md`. tmp + rename so a partially
 * written file never appears to cursor-agent if the process is interrupted.
 *
 * Returns the number of bytes written, or 0 when content is empty (no-op).
 */
export function writeAgentsMd(workspaceGroup: string, content: string): number {
  if (!content) return 0;
  const target = path.join(workspaceGroup, 'AGENTS.md');
  const tmp = target + '.tmp';
  fs.mkdirSync(workspaceGroup, { recursive: true });
  fs.writeFileSync(tmp, content);
  fs.renameSync(tmp, target);
  return Buffer.byteLength(content, 'utf-8');
}

// Test helpers (exported for unit tests).
export const __test__ = {
  buildSections,
  loadOptional,
};
